"""Removed current_session foreign key

Revision ID: 3552c894f374
Revises: 5237a0394435
Create Date: 2023-12-28 19:59:47.508634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3552c894f374'
down_revision = '5237a0394435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('users_ibfk_1', 'sessions', ['current_session'], ['id'])

    # ### end Alembic commands ###
