"""Added Foreign Keys

Revision ID: 4033840ccc96
Revises: 19fe24ef317c
Create Date: 2023-12-27 15:56:12.279056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4033840ccc96'
down_revision = '19fe24ef317c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player_num', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('pokedex_num',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=False)
        batch_op.alter_column('sprite_variant',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=2),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('link_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sessions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessions', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('type_1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('link_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('sprite_variant',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('pokedex_num',
               existing_type=sa.String(length=9),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player_num')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
