"""Added current_session column to Users

Revision ID: dc70cf47af87
Revises: 4033840ccc96
Create Date: 2023-12-28 19:28:12.836143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc70cf47af87'
down_revision = '4033840ccc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.drop_column('session_num')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_session')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_num', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
